import SwiftUI

struct CommunityPost: Identifiable, Codable {
    var id = UUID()
    let authorName: String
    let authorAvatar: String
    let timestamp: Date
    let content: String
    let postType: PostType
    let location: String?
    let urgency: UrgencyLevel
    var likes: Int
    var comments: [Comment]
    var isVerified: Bool
    var isLikedByUser: Bool = false
    var isMyPost: Bool = false
    var isAutoGenerated: Bool = false

    enum PostType: String, CaseIterable, Codable {
        case help = "Help Needed"
        case offer = "Offering Help"
        case info = "Information"
        case evacuation = "Evacuation"
        case shelter = "Shelter"
        case resources = "Resources"

        var icon: String {
            switch self {
            case .help: return "hand.raised.fill"
            case .offer: return "heart.fill"
            case .info: return "info.circle.fill"
            case .evacuation: return "exclamationmark.triangle.fill"
            case .shelter: return "house.fill"
            case .resources: return "archivebox.fill"
            }
        }

        var color: Color {
            switch self {
            case .help: return Color(red: 1.0, green: 0.0, blue: 0.0)
            case .offer: return Color(red: 0.0, green: 0.8, blue: 0.0)
            case .info: return Color(red: 0.0, green: 0.6, blue: 1.0)
            case .evacuation: return Color(red: 1.0, green: 0.5, blue: 0.0)
            case .shelter: return Color(red: 0.5, green: 0.0, blue: 1.0)
            case .resources: return Color(red: 1.0, green: 0.8, blue: 0.0)
            }
        }
    }

    enum UrgencyLevel: String, CaseIterable, Codable {
        case low = "Low"
        case medium = "Medium"
        case high = "High"
        case critical = "Critical"

        var color: Color {
            switch self {
            case .low: return .green
            case .medium: return .yellow
            case .high: return .orange
            case .critical: return .red
            }
        }
    }
}

struct Comment: Identifiable, Codable {
    var id = UUID()
    let authorName: String
    let content: String
    let timestamp: Date
    var likes: Int
}

struct CommunityThreadsView: View {

    @State private var posts: [CommunityPost] = []
    @State private var newPostContent = ""
    @State private var selectedPostType: CommunityPost.PostType = .help
    @State private var selectedUrgency: CommunityPost.UrgencyLevel = .medium
    @State private var showNewPostSheet = false
    @State private var selectedFilter: CommunityPost.PostType? = nil
    @State private var selectedPost: CommunityPost? = nil
    @State private var showPostDetail = false
    @State private var isLoading = false
    @State private var refreshing = false

    @State private var lastAutoPostDate: Date?
    @State private var autoPostTimer: Timer?

    var body: some View {
        NavigationStack {
            ZStack {

                Color.appGradientBackground
                    .ignoresSafeArea()

                VStack(spacing: 0) {

                    modernHeaderView

                    if !filteredPosts.isEmpty {
                        filterPillsView
                    }

                    if isLoading {
                        loadingView
                    } else {
                        postsScrollView
                    }
                }
            }
            .navigationBarHidden(true)
            .sheet(isPresented: $showNewPostSheet) {
                NewPostSheet(
                    content: $newPostContent,
                    postType: $selectedPostType,
                    urgency: $selectedUrgency,
                    onPost: createNewPost
                )
            }
            .sheet(isPresented: $showPostDetail, onDismiss: {
                selectedPost = nil
            }) {
                if let post = selectedPost {
                    PostDetailView(post: post) { action in
                        handlePostAction(action, for: post)

                        if let index = posts.firstIndex(where: { $0.id == post.id }) {
                            selectedPost = posts[index]
                        }
                    } onCommentsUpdate: { updatedComments in

                        if let index = posts.firstIndex(where: { $0.id == post.id }) {
                            posts[index].comments = updatedComments
                            selectedPost = posts[index]
                            savePosts()
                        }
                    }
                }
            }
            .presentationBackground(Color.appBackground)
            .onChange(of: showPostDetail) { _, isPresented in
                if !isPresented {
                    selectedPost = nil
                }
            }
            .onAppear {
                setupLocalStorage()
                setupAutoPostSystem()
            }
            .onDisappear {
                autoPostTimer?.invalidate()
            }
        }
    }

    private var modernHeaderView: some View {
        VStack(spacing: 18) {
            HStack {
                Text(" Community")
                    .font(.appTitle)
                    .foregroundColor(.appTextPrimary)

                Spacer()

                HStack(spacing: 16) {

                    Button(action: {
                        withAnimation(.appSpring) {
                            refreshPosts()
                        }
                    }) {
                        Image(systemName: refreshing ? "arrow.clockwise" : "arrow.clockwise")
                            .font(.system(size: 18, weight: .medium))
                            .foregroundColor(.appPrimary)
                            .rotationEffect(.degrees(refreshing ? 360 : 0))
                            .animation(refreshing ? .linear(duration: 1).repeatForever(autoreverses: false) : .none, value: refreshing)
                    }

                    Button(action: {
                        showNewPostSheet = true
                    }) {
                        Image(systemName: "plus.circle.fill")
                            .font(.system(size: 20, weight: .medium))
                            .foregroundColor(.appPrimary)
                    }
                }
            }

            HStack(spacing: 4) {
                StatChip(
                    icon: "person.3.fill",
                    value: "\(posts.count)",
                    label: "Posts"
                )

                StatChip(
                    icon: "heart.fill",
                    value: "\(totalLikes)",
                    label: "Likes"
                )

                StatChip(
                    icon: "bubble.left.fill",
                    value: "\(totalComments)",
                    label: "Replies"
                )

                Spacer()
            }
        }
        .padding(.horizontal, 7)
        .padding(.top, 8)
        .padding(.bottom, 16)
    }

    private var filterPillsView: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 12) {
                ModernFilterPill(
                    title: "All",
                    icon: "circle.grid.2x2.fill",
                    isSelected: selectedFilter == nil,
                    count: posts.count
                ) {
                    withAnimation(.appEaseOut) {
                        selectedFilter = nil
                    }
                }

                ForEach(CommunityPost.PostType.allCases, id: \.self) { postType in
                    ModernFilterPill(
                        title: postType.rawValue.components(separatedBy: " ").first ?? postType.rawValue,
                        icon: postType.icon,
                        isSelected: selectedFilter == postType,
                        count: posts.filter { $0.postType == postType }.count
                    ) {
                        withAnimation(.appEaseOut) {
                            selectedFilter = postType
                        }
                    }
                }
            }
            .padding(.horizontal, 20)
        }
        .padding(.vertical, 8)
    }

    private var loadingView: some View {
        VStack(spacing: 16) {
            ProgressView()
                .progressViewStyle(CircularProgressViewStyle(tint: .appPrimary))
                .scaleEffect(1.2)

            Text("Loading community...")
                .font(.appCaption)
                .foregroundColor(.appTextSecondary)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .padding(.top, 100)
    }

    private var postsScrollView: some View {
        ScrollView(.vertical, showsIndicators: false) {
            LazyVStack(spacing: 12) {
                if filteredPosts.isEmpty {
                    emptyStateView
                } else {
                    ForEach(filteredPosts) { post in
                        ThreadCard(post: post) { action in
                            withAnimation(.appEaseOut) {
                                handlePostAction(action, for: post)
                            }
                        }
                        .onTapGesture {
                            selectedPost = post
                            showPostDetail = true
                        }
                    }
                }
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 8)
        }
        .refreshable {
            await refreshPostsAsync()
        }
    }

    private var emptyStateView: some View {
        VStack(spacing: 20) {
            Image(systemName: "bubble.left.and.bubble.right")
                .font(.system(size: 48))
                .foregroundColor(.appTextTertiary)

            VStack(spacing: 8) {
                Text("No posts yet")
                    .font(.appHeadline)
                    .foregroundColor(.appTextPrimary)

                Text("Be the first to share something with the community")
                    .font(.appCaption)
                    .foregroundColor(.appTextSecondary)
                    .multilineTextAlignment(.center)
            }

            Button(action: {
                showNewPostSheet = true
            }) {
                Text("Create Post")
                    .font(.appSubheadline)
                    .fontWeight(.medium)
            }
            .appButtonPrimary()
        }
        .padding(40)
        .frame(maxWidth: .infinity)
    }

    private var filteredPosts: [CommunityPost] {
        var filtered = posts

        if let filter = selectedFilter {
            filtered = filtered.filter { $0.postType == filter }
        }

        return filtered.sorted { $0.timestamp > $1.timestamp }
    }

    private var totalLikes: Int {
        posts.reduce(0) { $0 + $1.likes }
    }

    private var totalComments: Int {
        posts.reduce(0) { $0 + $1.comments.count }
    }

    private func handlePostAction(_ action: PostAction, for post: CommunityPost) {
        switch action {
        case .like:
            if let index = posts.firstIndex(where: { $0.id == post.id }) {
                posts[index].isLikedByUser.toggle()
                if posts[index].isLikedByUser {
                    posts[index].likes += 1
                } else {
                    posts[index].likes -= 1
                }
                savePosts()
            }
        case .comment:

            selectedPost = post
            showPostDetail = true
        case .share:
            sharePost(post)
        case .delete:
            deletePost(post)
        }
    }

    private func setupLocalStorage() {

        loadPosts()
        isLoading = false
    }

    private func createNewPost() {
        let newPost = CommunityPost(
            authorName: "You",
            authorAvatar: "person.crop.circle.fill",
            timestamp: Date(),
            content: newPostContent,
            postType: selectedPostType,
            location: "Current Location",
            urgency: selectedUrgency,
            likes: 0,
            comments: [],
            isVerified: false,
            isLikedByUser: false,
            isMyPost: true
        )

        posts.insert(newPost, at: 0)
        savePosts()

        newPostContent = ""
        selectedPostType = .help
        selectedUrgency = .medium
        showNewPostSheet = false
    }

    private func deletePost(_ post: CommunityPost) {
        posts.removeAll { $0.id == post.id }
        savePosts()
    }

    private func refreshPosts() {
        refreshing = true

        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
            loadPosts()
            refreshing = false
        }
    }

    @MainActor
    private func refreshPostsAsync() async {
        refreshing = true

        try? await Task.sleep(nanoseconds: 1_000_000_000)
        loadPosts()
        refreshing = false
    }

    private func sharePost(_ post: CommunityPost) {

        let shareText = createShareText(for: post)

        let activityVC = UIActivityViewController(
            activityItems: [shareText],
            applicationActivities: nil
        )

        if let popover = activityVC.popoverPresentationController {
            popover.sourceView = UIApplication.shared.connectedScenes
                .compactMap { $0 as? UIWindowScene }
                .flatMap { $0.windows }
                .first { $0.isKeyWindow }
            popover.sourceRect = CGRect(x: UIScreen.main.bounds.midX, y: UIScreen.main.bounds.midY, width: 0, height: 0)
            popover.permittedArrowDirections = []
        }

        DispatchQueue.main.async {
            if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
               let window = windowScene.windows.first,
               let rootVC = window.rootViewController {

                var topVC = rootVC
                while let presentedVC = topVC.presentedViewController {
                    topVC = presentedVC
                }

                topVC.present(activityVC, animated: true)
            }
        }
    }

    private func createShareText(for post: CommunityPost) -> String {
        var shareText = "🔥 Wildfire Community Update\n\n"
        shareText += "📝 \(post.postType.rawValue)\n"
        shareText += "👤 \(post.authorName)\n"
        shareText += "🚨 Urgency: \(post.urgency.rawValue)\n"

        if let location = post.location {
            shareText += "📍 Location: \(location)\n"
        }

        shareText += "\n💬 \(post.content)\n"
        shareText += "\n💬 Comments: \(post.comments.count)\n"
        shareText += "❤️ Likes: \(post.likes)\n"

        shareText += "\n📱 Shared from Ignis - Wildfire Community App"

        return shareText
    }

    private func savePosts() {
        if let encoded = try? JSONEncoder().encode(posts) {
            UserDefaults.standard.set(encoded, forKey: "communityPosts")
        }
    }

    private func loadPosts() {
        if let data = UserDefaults.standard.data(forKey: "communityPosts"),
           let decoded = try? JSONDecoder().decode([CommunityPost].self, from: data) {
            posts = decoded
        } else {

            loadSamplePosts()
        }
    }

    private func loadSamplePosts() {
        posts = [

            CommunityPost(
                authorName: "Sarah Johnson",
                authorAvatar: "person.crop.circle.fill",
                timestamp: Date().addingTimeInterval(-1800),
                content: "🚨 URGENT: Need help evacuating elderly parents from North County. Anyone with a vehicle available? We're near the evacuation zone and need assistance getting them to safety.",
                postType: .help,
                location: "North County, CA",
                urgency: .critical,
                likes: 24,
                comments: [
                    Comment(authorName: "Mike Chen", content: "I'm 10 minutes away. DM me your address.", timestamp: Date().addingTimeInterval(-900), likes: 8),
                    Comment(authorName: "Fire Dept", content: "Emergency services are in the area. Call 911 if immediate assistance needed.", timestamp: Date().addingTimeInterval(-600), likes: 15),
                    Comment(authorName: "Local Volunteer", content: "I have a van and can help transport. What's the exact location?", timestamp: Date().addingTimeInterval(-450), likes: 12),
                    Comment(authorName: "Sarah Johnson", content: "Thank you everyone! We're at 123 Oak Street. Mike is on his way.", timestamp: Date().addingTimeInterval(-300), likes: 6),
                    Comment(authorName: "Medical Transport", content: "We have wheelchair-accessible vehicles if needed.", timestamp: Date().addingTimeInterval(-180), likes: 9),
                    Comment(authorName: "Community Support", content: "Praying for your family's safety. Let us know when you're out.", timestamp: Date().addingTimeInterval(-120), likes: 14),
                    Comment(authorName: "Emergency Coordinator", content: "Zone evacuation complete. All residents accounted for.", timestamp: Date().addingTimeInterval(-60), likes: 22)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Red Cross Shelter",
                authorAvatar: "cross.fill",
                timestamp: Date().addingTimeInterval(-3600),
                content: "🏠 SHELTER UPDATE: Red Cross shelter now open at Central High School. Food, water, and medical assistance available. Pets welcome. Capacity: 200 people.",
                postType: .shelter,
                location: "Central High School",
                urgency: .high,
                likes: 156,
                comments: [
                    Comment(authorName: "Local Volunteer", content: "I'm here helping coordinate. We have plenty of space and supplies.", timestamp: Date().addingTimeInterval(-1800), likes: 23),
                    Comment(authorName: "Maria Garcia", content: "Do you have baby formula and diapers?", timestamp: Date().addingTimeInterval(-1200), likes: 5),
                    Comment(authorName: "Red Cross Shelter", content: "Yes, we have baby supplies and formula. Come to the main entrance.", timestamp: Date().addingTimeInterval(-900), likes: 18),
                    Comment(authorName: "Pet Rescue", content: "We have pet food and crates available too.", timestamp: Date().addingTimeInterval(-600), likes: 12),
                    Comment(authorName: "Medical Team", content: "Free health screenings available. No appointment needed.", timestamp: Date().addingTimeInterval(-300), likes: 15)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "David Martinez",
                authorAvatar: "person.crop.circle.badge.plus",
                timestamp: Date().addingTimeInterval(-5400),
                content: "💧 Offering free water and supplies to anyone in need. I have cases of water, masks, and first aid kits. Located at the community center parking lot.",
                postType: .offer,
                location: "Community Center",
                urgency: .medium,
                likes: 89,
                comments: [
                    Comment(authorName: "Lisa Park", content: "Thank you so much! This is a lifesaver.", timestamp: Date().addingTimeInterval(-2700), likes: 12),
                    Comment(authorName: "John Smith", content: "I can help distribute. Be there in 15 min.", timestamp: Date().addingTimeInterval(-1800), likes: 7),
                    Comment(authorName: "Local Church", content: "We can provide additional volunteers for distribution.", timestamp: Date().addingTimeInterval(-1200), likes: 9),
                    Comment(authorName: "David Martinez", content: "Great! The more help the better. We're running low on masks.", timestamp: Date().addingTimeInterval(-900), likes: 5),
                    Comment(authorName: "Community Center", content: "We have space for more supplies if needed.", timestamp: Date().addingTimeInterval(-600), likes: 8),
                    Comment(authorName: "Health Dept", content: "Thank you for providing essential supplies during this crisis.", timestamp: Date().addingTimeInterval(-300), likes: 15)
                ],
                isVerified: false,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Fire Department",
                authorAvatar: "flame.circle.fill",
                timestamp: Date().addingTimeInterval(-7200),
                content: "🔥 FIRE UPDATE: Containment at 45%. Winds shifting NW. New evacuation orders for Zone 3. Stay alert and follow official instructions.",
                postType: .info,
                location: "Zone 3",
                urgency: .high,
                likes: 234,
                comments: [
                    Comment(authorName: "Weather Service", content: "Wind speeds expected to increase to 25mph by evening.", timestamp: Date().addingTimeInterval(-3600), likes: 18),
                    Comment(authorName: "Emergency Services", content: "Additional fire crews arriving from neighboring counties.", timestamp: Date().addingTimeInterval(-2700), likes: 25),
                    Comment(authorName: "Local Resident", content: "Can see the smoke from my house. Stay safe everyone!", timestamp: Date().addingTimeInterval(-1800), likes: 12),
                    Comment(authorName: "Fire Department", content: "Update: Containment now at 52%. Progress being made.", timestamp: Date().addingTimeInterval(-900), likes: 31),
                    Comment(authorName: "Police Dept", content: "Road closures in effect. Follow official evacuation routes.", timestamp: Date().addingTimeInterval(-600), likes: 19),
                    Comment(authorName: "Community Alert", content: "Air quality index at 175. Consider wearing masks.", timestamp: Date().addingTimeInterval(-300), likes: 14)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Amanda Wilson",
                authorAvatar: "person.crop.circle.badge.questionmark",
                timestamp: Date().addingTimeInterval(-9000),
                content: "🐕 Lost my dog during evacuation. Golden retriever named Max, last seen near Oak Street. He's friendly and wearing a red collar. Please help find him!",
                postType: .help,
                location: "Oak Street Area",
                urgency: .high,
                likes: 67,
                comments: [
                    Comment(authorName: "Pet Rescue Team", content: "We're searching the area. Will keep you updated.", timestamp: Date().addingTimeInterval(-4500), likes: 22),
                    Comment(authorName: "Local Resident", content: "Saw a golden retriever near the park 30 min ago. Will try to approach.", timestamp: Date().addingTimeInterval(-3000), likes: 14),
                    Comment(authorName: "Amanda Wilson", content: "Thank you! He responds to 'Max' and loves treats.", timestamp: Date().addingTimeInterval(-2400), likes: 8),
                    Comment(authorName: "Animal Control", content: "We have a golden retriever at our shelter. Will check if it's Max.", timestamp: Date().addingTimeInterval(-1800), likes: 16),
                    Comment(authorName: "Vet Clinic", content: "We can scan for microchip if found. Free service during emergency.", timestamp: Date().addingTimeInterval(-1200), likes: 11),
                    Comment(authorName: "Community Volunteer", content: "Posting Max's photo on local lost pet groups.", timestamp: Date().addingTimeInterval(-600), likes: 9),
                    Comment(authorName: "Amanda Wilson", content: "FOUND HIM! Thank you everyone for your help! ❤️", timestamp: Date().addingTimeInterval(-300), likes: 45)
                ],
                isVerified: false,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Community Pharmacy",
                authorAvatar: "pills.fill",
                timestamp: Date().addingTimeInterval(-10800),
                content: "💊 FREE MEDICATIONS: We have emergency supplies of inhalers, insulin, and other essential medications. No prescription needed during emergency. Open 24/7.",
                postType: .resources,
                location: "Downtown Pharmacy",
                urgency: .medium,
                likes: 189,
                comments: [
                    Comment(authorName: "Dr. Thompson", content: "I'm here to help with prescriptions and medical advice.", timestamp: Date().addingTimeInterval(-5400), likes: 31),
                    Comment(authorName: "Local Nurse", content: "Can help with wound care and basic first aid.", timestamp: Date().addingTimeInterval(-3600), likes: 19),
                    Comment(authorName: "Patient", content: "Thank you! Got my asthma medication. Lifesaver!", timestamp: Date().addingTimeInterval(-2700), likes: 15),
                    Comment(authorName: "Community Pharmacy", content: "We're restocking daily. Don't hesitate to ask for help.", timestamp: Date().addingTimeInterval(-1800), likes: 12),
                    Comment(authorName: "Medical Supply", content: "Donating additional supplies tomorrow morning.", timestamp: Date().addingTimeInterval(-900), likes: 8)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Emergency Services",
                authorAvatar: "exclamationmark.octagon.fill",
                timestamp: Date().addingTimeInterval(-1200),
                content: "🚨 MANDATORY EVACUATION: Zone 4 residents must evacuate immediately. Fire approaching rapidly. Take only essential items. Emergency shelters available.",
                postType: .evacuation,
                location: "Zone 4",
                urgency: .critical,
                likes: 445,
                comments: [
                    Comment(authorName: "Police Dept", content: "Officers are going door-to-door to ensure evacuation.", timestamp: Date().addingTimeInterval(-600), likes: 67),
                    Comment(authorName: "Bus Service", content: "Free evacuation buses running every 15 minutes from Main St.", timestamp: Date().addingTimeInterval(-300), likes: 89),
                    Comment(authorName: "Fire Chief", content: "Fire is 2 miles from Zone 4. Evacuate NOW.", timestamp: Date().addingTimeInterval(-240), likes: 156),
                    Comment(authorName: "Local Resident", content: "Leaving now. Where should we go?", timestamp: Date().addingTimeInterval(-180), likes: 23),
                    Comment(authorName: "Emergency Services", content: "Go to Central High School shelter. Buses available.", timestamp: Date().addingTimeInterval(-120), likes: 45),
                    Comment(authorName: "Weather Alert", content: "Winds shifting. Fire moving faster than expected.", timestamp: Date().addingTimeInterval(-60), likes: 78)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Tech Support Group",
                authorAvatar: "laptopcomputer.and.iphone",
                timestamp: Date().addingTimeInterval(-14400),
                content: "💻 FREE TECH SUPPORT: Offering help with emergency communications, setting up alerts, and device charging. We have solar chargers and WiFi hotspots available.",
                postType: .offer,
                location: "Library Parking Lot",
                urgency: .low,
                likes: 45,
                comments: [
                    Comment(authorName: "Local IT Guy", content: "Can help with emergency contact setup and GPS tracking.", timestamp: Date().addingTimeInterval(-7200), likes: 12),
                    Comment(authorName: "Library Staff", content: "We have free WiFi and charging stations inside.", timestamp: Date().addingTimeInterval(-5400), likes: 8),
                    Comment(authorName: "Emergency Contact", content: "Need help setting up family emergency contacts.", timestamp: Date().addingTimeInterval(-3600), likes: 5),
                    Comment(authorName: "Tech Support Group", content: "Come by anytime. We're here until 8pm.", timestamp: Date().addingTimeInterval(-1800), likes: 6),
                    Comment(authorName: "Local Resident", content: "Thanks for the help with my phone alerts!", timestamp: Date().addingTimeInterval(-900), likes: 4)
                ],
                isVerified: false,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Animal Shelter",
                authorAvatar: "pawprint.circle.fill",
                timestamp: Date().addingTimeInterval(-16200),
                content: "🐾 PET SHELTER: Temporary pet shelter open at County Fairgrounds. We have food, water, and kennels. Volunteers needed to help care for evacuated pets.",
                postType: .shelter,
                location: "County Fairgrounds",
                urgency: .medium,
                likes: 123,
                comments: [
                    Comment(authorName: "Vet Clinic", content: "Providing free medical care for injured pets.", timestamp: Date().addingTimeInterval(-8100), likes: 28),
                    Comment(authorName: "Pet Food Donation", content: "Donating 500lbs of pet food. Will deliver this afternoon.", timestamp: Date().addingTimeInterval(-5400), likes: 15),
                    Comment(authorName: "Volunteer", content: "I can help walk dogs and clean kennels.", timestamp: Date().addingTimeInterval(-3600), likes: 12),
                    Comment(authorName: "Animal Shelter", content: "Great! We need volunteers for 2-hour shifts.", timestamp: Date().addingTimeInterval(-2700), likes: 8),
                    Comment(authorName: "Pet Owner", content: "My cat is there. Thank you for taking care of her!", timestamp: Date().addingTimeInterval(-1800), likes: 11),
                    Comment(authorName: "Local Business", content: "Donating blankets and toys for the pets.", timestamp: Date().addingTimeInterval(-900), likes: 9)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Elderly Care Center",
                authorAvatar: "heart.circle.fill",
                timestamp: Date().addingTimeInterval(-18000),
                content: "👴 NEED VOLUNTEERS: Looking for people to help transport elderly residents to shelters. Many need assistance with mobility and medical equipment.",
                postType: .help,
                location: "Sunset Senior Center",
                urgency: .medium,
                likes: 78,
                comments: [
                    Comment(authorName: "Medical Transport", content: "We have wheelchair-accessible vans available.", timestamp: Date().addingTimeInterval(-9000), likes: 21),
                    Comment(authorName: "Nursing Student", content: "Can help with basic medical monitoring during transport.", timestamp: Date().addingTimeInterval(-6000), likes: 13),
                    Comment(authorName: "Volunteer Driver", content: "I can help with transportation. Have experience with elderly care.", timestamp: Date().addingTimeInterval(-4500), likes: 16),
                    Comment(authorName: "Elderly Care Center", content: "Thank you! We need help starting at 8am tomorrow.", timestamp: Date().addingTimeInterval(-3600), likes: 9),
                    Comment(authorName: "Local Church", content: "Our congregation can provide additional volunteers.", timestamp: Date().addingTimeInterval(-2700), likes: 11),
                    Comment(authorName: "Family Member", content: "My grandmother is there. Thank you for the help!", timestamp: Date().addingTimeInterval(-1800), likes: 8),
                    Comment(authorName: "Healthcare Worker", content: "Can assist with medication management during transport.", timestamp: Date().addingTimeInterval(-900), likes: 12)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Weather Service",
                authorAvatar: "cloud.sun.rain.fill",
                timestamp: Date().addingTimeInterval(-21600),
                content: "🌤️ WEATHER UPDATE: Humidity levels dropping to 15%. Fire danger remains extreme. No rain expected for next 5 days. Stay hydrated and avoid outdoor activities.",
                postType: .info,
                location: "Regional",
                urgency: .low,
                likes: 156,
                comments: [
                    Comment(authorName: "Health Dept", content: "Air quality index at 150. Consider wearing masks outdoors.", timestamp: Date().addingTimeInterval(-10800), likes: 34),
                    Comment(authorName: "Local Resident", content: "Thanks for the update. Staying inside today.", timestamp: Date().addingTimeInterval(-8100), likes: 12),
                    Comment(authorName: "Weather Service", content: "Wind speeds expected to increase this afternoon.", timestamp: Date().addingTimeInterval(-5400), likes: 18),
                    Comment(authorName: "Emergency Prep", content: "Good time to check emergency supplies.", timestamp: Date().addingTimeInterval(-3600), likes: 8),
                    Comment(authorName: "Community Alert", content: "Water conservation recommended due to low humidity.", timestamp: Date().addingTimeInterval(-1800), likes: 15)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Food Bank",
                authorAvatar: "cart.circle.fill",
                timestamp: Date().addingTimeInterval(-25200),
                content: "🍎 FREE FOOD DISTRIBUTION: Fresh produce, canned goods, and ready-to-eat meals available. No ID required. Serving 500+ families daily. Volunteers welcome.",
                postType: .resources,
                location: "Community Food Bank",
                urgency: .high,
                likes: 234,
                comments: [
                    Comment(authorName: "Local Restaurant", content: "Donating 200 hot meals daily. Will continue as long as needed.", timestamp: Date().addingTimeInterval(-12600), likes: 45),
                    Comment(authorName: "Farmer's Market", content: "Bringing fresh produce tomorrow morning.", timestamp: Date().addingTimeInterval(-9000), likes: 23),
                    Comment(authorName: "Volunteer", content: "I can help distribute food. What time do you need people?", timestamp: Date().addingTimeInterval(-7200), likes: 18),
                    Comment(authorName: "Food Bank", content: "We need volunteers from 8am-6pm daily.", timestamp: Date().addingTimeInterval(-5400), likes: 12),
                    Comment(authorName: "Local Family", content: "Thank you for the food! It's helping us get through this.", timestamp: Date().addingTimeInterval(-3600), likes: 31),
                    Comment(authorName: "Grocery Store", content: "Donating canned goods and non-perishables.", timestamp: Date().addingTimeInterval(-1800), likes: 16),
                    Comment(authorName: "Community Support", content: "Can help with food preparation and packaging.", timestamp: Date().addingTimeInterval(-900), likes: 14)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Construction Company",
                authorAvatar: "hammer.circle.fill",
                timestamp: Date().addingTimeInterval(-28800),
                content: "🏗️ FREE CLEANUP SERVICES: Offering heavy equipment and labor for post-fire cleanup. Bulldozers, excavators, and dump trucks available. Contact for scheduling.",
                postType: .offer,
                location: "Affected Areas",
                urgency: .high,
                likes: 167,
                comments: [
                    Comment(authorName: "Insurance Agent", content: "Can help with damage assessment and claims documentation.", timestamp: Date().addingTimeInterval(-14400), likes: 29),
                    Comment(authorName: "Debris Removal", content: "Specialized in hazardous material cleanup and disposal.", timestamp: Date().addingTimeInterval(-10800), likes: 18),
                    Comment(authorName: "Homeowner", content: "Need help clearing debris from my property. How do I contact you?", timestamp: Date().addingTimeInterval(-7200), likes: 12),
                    Comment(authorName: "Construction Company", content: "Call our emergency line: 555-0123. Available 24/7.", timestamp: Date().addingTimeInterval(-5400), likes: 15),
                    Comment(authorName: "Local Government", content: "Coordinating with FEMA for additional cleanup resources.", timestamp: Date().addingTimeInterval(-3600), likes: 22),
                    Comment(authorName: "Safety Inspector", content: "Can help assess structural integrity of damaged buildings.", timestamp: Date().addingTimeInterval(-1800), likes: 19)
                ],
                isVerified: false,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Local School",
                authorAvatar: "graduationcap.circle.fill",
                timestamp: Date().addingTimeInterval(-32400),
                content: "📚 NEED SCHOOL SUPPLIES: Students displaced by fires need backpacks, notebooks, and basic supplies. Donations can be dropped off at temporary school location.",
                postType: .help,
                location: "Temporary School Site",
                urgency: .low,
                likes: 89,
                comments: [
                    Comment(authorName: "Office Supply Store", content: "Donating 100 backpacks and school supplies.", timestamp: Date().addingTimeInterval(-16200), likes: 25),
                    Comment(authorName: "Parent Volunteer", content: "Can help organize and distribute supplies.", timestamp: Date().addingTimeInterval(-10800), likes: 12),
                    Comment(authorName: "Local School", content: "Thank you! We also need laptops for online learning.", timestamp: Date().addingTimeInterval(-8100), likes: 18),
                    Comment(authorName: "Tech Company", content: "Donating 50 refurbished laptops for students.", timestamp: Date().addingTimeInterval(-5400), likes: 31),
                    Comment(authorName: "Teacher", content: "Can help set up virtual classrooms and online resources.", timestamp: Date().addingTimeInterval(-3600), likes: 14),
                    Comment(authorName: "Student", content: "Thank you for the supplies! It helps us keep learning.", timestamp: Date().addingTimeInterval(-1800), likes: 9)
                ],
                isVerified: true,
                isLikedByUser: false
            ),

            CommunityPost(
                authorName: "Mental Health Services",
                authorAvatar: "brain.head.profile.fill",
                timestamp: Date().addingTimeInterval(-36000),
                content: "🧠 CRISIS COUNSELING: Free mental health support available for fire survivors. Trauma counselors, support groups, and 24/7 crisis hotline. You're not alone.",
                postType: .info,
                location: "Multiple Locations",
                urgency: .medium,
                likes: 198,
                comments: [
                    Comment(authorName: "Licensed Therapist", content: "Specializing in trauma and PTSD. Available for individual sessions.", timestamp: Date().addingTimeInterval(-18000), likes: 42),
                    Comment(authorName: "Support Group", content: "Daily group sessions at 2pm and 7pm. Childcare provided.", timestamp: Date().addingTimeInterval(-14400), likes: 31),
                    Comment(authorName: "Crisis Hotline", content: "24/7 support available at 1-800-CRISIS. Confidential and free.", timestamp: Date().addingTimeInterval(-10800), likes: 28),
                    Comment(authorName: "Survivor", content: "The counseling helped me process the trauma. Thank you.", timestamp: Date().addingTimeInterval(-7200), likes: 35),
                    Comment(authorName: "Mental Health Services", content: "We also offer family counseling and children's therapy.", timestamp: Date().addingTimeInterval(-5400), likes: 19),
                    Comment(authorName: "Community Member", content: "Can help with transportation to counseling sessions.", timestamp: Date().addingTimeInterval(-3600), likes: 12),
                    Comment(authorName: "Volunteer", content: "Available to provide emotional support and companionship.", timestamp: Date().addingTimeInterval(-1800), likes: 15)
                ],
                isVerified: true,
                isLikedByUser: false
            )
        ]
    }

    private func setupAutoPostSystem() {

        if let savedDate = UserDefaults.standard.object(forKey: "lastAutoPostDate") as? Date {
            lastAutoPostDate = savedDate
        } else {
            lastAutoPostDate = Date().addingTimeInterval(-86400)
        }

        checkAndAddDailyPosts()

        autoPostTimer = Timer.scheduledTimer(withTimeInterval: 3600, repeats: true) { _ in
            checkAndAddDailyPosts()
        }
    }

    private func checkAndAddDailyPosts() {
        let calendar = Calendar.current
        let today = Date()

        if let lastDate = lastAutoPostDate,
           calendar.isDate(lastDate, inSameDayAs: today) {
            return
        }

        let numberOfPosts = Int.random(in: 2...3)
        addDailyAutoPosts(count: numberOfPosts)

        lastAutoPostDate = today
        UserDefaults.standard.set(today, forKey: "lastAutoPostDate")
    }

    private func addDailyAutoPosts(count: Int) {
        let newPosts = generateDailyPosts(count: count)

        posts.insert(contentsOf: newPosts, at: 0)
        savePosts()

        print("📅 Added \(count) new auto-generated posts for today")
    }

    private func generateDailyPosts(count: Int) -> [CommunityPost] {
        let postTemplates = getDailyPostTemplates()
        var newPosts: [CommunityPost] = []

        let shuffledTemplates = postTemplates.shuffled()

        for i in 0..<count {
            let template = shuffledTemplates[i % shuffledTemplates.count]
            let post = createPostFromTemplate(template)
            newPosts.append(post)
        }

        return newPosts
    }

    private func getDailyPostTemplates() -> [DailyPostTemplate] {
        return [

            DailyPostTemplate(
                authorName: "Local Resident",
                authorAvatar: "person.crop.circle.badge.questionmark",
                content: "🚨 Need help with elderly neighbor evacuation. Anyone available to assist? She has mobility issues and needs help getting to the shelter.",
                postType: .help,
                location: "Oak Street Area",
                urgency: .high,
                isVerified: false
            ),
            DailyPostTemplate(
                authorName: "Pet Owner",
                authorAvatar: "pawprint.circle.fill",
                content: "🐕 Lost my dog during evacuation. Golden retriever named Buddy, last seen near Main Street. He's friendly and wearing a blue collar. Please help!",
                postType: .help,
                location: "Main Street Area",
                urgency: .medium,
                isVerified: false
            ),

            DailyPostTemplate(
                authorName: "Community Volunteer",
                authorAvatar: "person.crop.circle.badge.plus",
                content: "💧 Offering free water and supplies to anyone in need. I have cases of water, masks, and first aid kits. Located at the community center.",
                postType: .offer,
                location: "Community Center",
                urgency: .medium,
                isVerified: false
            ),
            DailyPostTemplate(
                authorName: "Local Business",
                authorAvatar: "building.2.crop.circle.fill",
                content: "🏠 FREE SHELTER: Our hotel has 20 rooms available for evacuees. Free WiFi, meals included. Contact front desk for arrangements.",
                postType: .offer,
                location: "Downtown Hotel",
                urgency: .high,
                isVerified: true
            ),

            DailyPostTemplate(
                authorName: "Weather Service",
                authorAvatar: "cloud.sun.rain.fill",
                content: "🌤️ WEATHER UPDATE: Humidity at 25%. Fire danger remains high. Winds expected to shift NW by evening. Stay alert.",
                postType: .info,
                location: "Regional",
                urgency: .medium,
                isVerified: true
            ),
            DailyPostTemplate(
                authorName: "Fire Department",
                authorAvatar: "flame.circle.fill",
                content: "🔥 FIRE UPDATE: Containment at 60%. New evacuation orders for Zone 2. Fire crews making good progress.",
                postType: .info,
                location: "Zone 2",
                urgency: .high,
                isVerified: true
            ),

            DailyPostTemplate(
                authorName: "Red Cross",
                authorAvatar: "cross.fill",
                content: "🏠 SHELTER UPDATE: Red Cross shelter open at Central High School. Food, water, medical assistance available. Pets welcome.",
                postType: .shelter,
                location: "Central High School",
                urgency: .high,
                isVerified: true
            ),
            DailyPostTemplate(
                authorName: "Animal Shelter",
                authorAvatar: "pawprint.circle.fill",
                content: "🐾 PET SHELTER: Temporary pet shelter open at County Fairgrounds. Food, water, and kennels available. Volunteers needed.",
                postType: .shelter,
                location: "County Fairgrounds",
                urgency: .medium,
                isVerified: true
            ),

            DailyPostTemplate(
                authorName: "Community Pharmacy",
                authorAvatar: "pills.fill",
                content: "💊 FREE MEDICATIONS: Emergency supplies of inhalers, insulin, and essential medications available. No prescription needed during emergency.",
                postType: .resources,
                location: "Downtown Pharmacy",
                urgency: .medium,
                isVerified: true
            ),
            DailyPostTemplate(
                authorName: "Food Bank",
                authorAvatar: "cart.circle.fill",
                content: "🍎 FREE FOOD DISTRIBUTION: Fresh produce, canned goods, and ready-to-eat meals available. No ID required. Serving 300+ families daily.",
                postType: .resources,
                location: "Community Food Bank",
                urgency: .high,
                isVerified: true
            ),

            DailyPostTemplate(
                authorName: "Emergency Services",
                authorAvatar: "exclamationmark.octagon.fill",
                content: "🚨 MANDATORY EVACUATION: Zone 3 residents must evacuate immediately. Fire approaching rapidly. Take only essential items.",
                postType: .evacuation,
                location: "Zone 3",
                urgency: .critical,
                isVerified: true
            )
        ]
    }

    private func createPostFromTemplate(_ template: DailyPostTemplate) -> CommunityPost {

        let comments = generateCommentsForPost(template.postType)

        let likes = Int.random(in: 5...50)

        let randomHoursAgo = Double.random(in: 1...24)
        let timestamp = Date().addingTimeInterval(-randomHoursAgo * 3600)

        let seasonalContent = addSeasonalVariations(to: template.content)

        return CommunityPost(
            authorName: template.authorName,
            authorAvatar: template.authorAvatar,
            timestamp: timestamp,
            content: seasonalContent,
            postType: template.postType,
            location: template.location,
            urgency: template.urgency,
            likes: likes,
            comments: comments,
            isVerified: template.isVerified,
            isLikedByUser: false,
            isMyPost: false,
            isAutoGenerated: true
        )
    }

    private func addSeasonalVariations(to content: String) -> String {
        let calendar = Calendar.current
        let month = calendar.component(.month, from: Date())

        switch month {
        case 6, 7, 8:
            if content.contains("WEATHER UPDATE") {
                return content.replacingOccurrences(of: "Humidity at 25%", with: "Humidity at 15%")
            }
            if content.contains("FIRE UPDATE") {
                return content.replacingOccurrences(of: "Containment at 60%", with: "Containment at 45%")
            }
        case 9, 10, 11:
            if content.contains("WEATHER UPDATE") {
                return content.replacingOccurrences(of: "Humidity at 25%", with: "Humidity at 35%")
            }
            if content.contains("FIRE UPDATE") {
                return content.replacingOccurrences(of: "Containment at 60%", with: "Containment at 70%")
            }
        case 12, 1, 2:
            if content.contains("WEATHER UPDATE") {
                return content.replacingOccurrences(of: "Humidity at 25%", with: "Humidity at 45%")
            }
            if content.contains("FIRE UPDATE") {
                return content.replacingOccurrences(of: "Containment at 60%", with: "Containment at 85%")
            }
        default:
            if content.contains("WEATHER UPDATE") {
                return content.replacingOccurrences(of: "Humidity at 25%", with: "Humidity at 30%")
            }
            if content.contains("FIRE UPDATE") {
                return content.replacingOccurrences(of: "Containment at 60%", with: "Containment at 55%")
            }
        }

        return content
    }

    private func generateCommentsForPost(_ postType: CommunityPost.PostType) -> [Comment] {
        let commentCount = Int.random(in: 3...6)
        var comments: [Comment] = []

        let commentTemplates = getCommentTemplates(for: postType)

        for i in 0..<commentCount {
            let template = commentTemplates[i % commentTemplates.count]
            let hoursAgo = Double.random(in: 0.5...6.0)
            let timestamp = Date().addingTimeInterval(-hoursAgo * 3600)
            let likes = Int.random(in: 1...15)

            let comment = Comment(
                authorName: template.authorName,
                content: template.content,
                timestamp: timestamp,
                likes: likes
            )
            comments.append(comment)
        }

        return comments
    }

    private func getCommentTemplates(for postType: CommunityPost.PostType) -> [CommentTemplate] {
        switch postType {
        case .help:
            return [
                CommentTemplate(authorName: "Local Volunteer", content: "I can help! DM me your location."),
                CommentTemplate(authorName: "Emergency Services", content: "We're in the area. Call 911 if immediate assistance needed."),
                CommentTemplate(authorName: "Community Member", content: "Praying for your safety. Let us know if you need anything."),
                CommentTemplate(authorName: "Neighbor", content: "I'm nearby and can assist. What do you need?"),
                CommentTemplate(authorName: "Medical Team", content: "We have medical supplies if needed."),
                CommentTemplate(authorName: "Transport Volunteer", content: "I have a vehicle and can help with transportation.")
            ]
        case .offer:
            return [
                CommentTemplate(authorName: "Local Resident", content: "Thank you so much! This is a lifesaver."),
                CommentTemplate(authorName: "Community Member", content: "I can help distribute. Be there in 15 min."),
                CommentTemplate(authorName: "Volunteer", content: "I can assist with coordination and distribution."),
                CommentTemplate(authorName: "Local Business", content: "We can provide additional supplies if needed."),
                CommentTemplate(authorName: "Emergency Coordinator", content: "Thank you for your generosity during this crisis."),
                CommentTemplate(authorName: "Community Support", content: "This is exactly what we need right now.")
            ]
        case .info:
            return [
                CommentTemplate(authorName: "Local Resident", content: "Thanks for the update. Staying informed."),
                CommentTemplate(authorName: "Weather Service", content: "Additional weather updates available on our website."),
                CommentTemplate(authorName: "Emergency Services", content: "We're monitoring the situation closely."),
                CommentTemplate(authorName: "Community Member", content: "Good to know. Stay safe everyone!"),
                CommentTemplate(authorName: "Local News", content: "We'll continue to provide updates as they come in."),
                CommentTemplate(authorName: "Fire Chief", content: "Crews are working hard to contain the fire.")
            ]
        case .shelter:
            return [
                CommentTemplate(authorName: "Local Volunteer", content: "I'm here helping coordinate. We have plenty of space."),
                CommentTemplate(authorName: "Shelter Resident", content: "Thank you for providing this safe space."),
                CommentTemplate(authorName: "Medical Team", content: "Free health screenings available. No appointment needed."),
                CommentTemplate(authorName: "Pet Rescue", content: "We have pet food and crates available too."),
                CommentTemplate(authorName: "Community Support", content: "Donating additional blankets and supplies."),
                CommentTemplate(authorName: "Volunteer", content: "Can help with food preparation and distribution.")
            ]
        case .resources:
            return [
                CommentTemplate(authorName: "Local Resident", content: "Thank you! Got my medication. Lifesaver!"),
                CommentTemplate(authorName: "Volunteer", content: "I can help distribute. What time do you need people?"),
                CommentTemplate(authorName: "Local Business", content: "We can provide additional supplies if needed."),
                CommentTemplate(authorName: "Community Member", content: "This is helping so many families. Thank you."),
                CommentTemplate(authorName: "Medical Team", content: "We have additional medical supplies to donate."),
                CommentTemplate(authorName: "Volunteer", content: "Can help with organization and distribution.")
            ]
        case .evacuation:
            return [
                CommentTemplate(authorName: "Police Dept", content: "Officers are going door-to-door to ensure evacuation."),
                CommentTemplate(authorName: "Bus Service", content: "Free evacuation buses running every 15 minutes."),
                CommentTemplate(authorName: "Fire Chief", content: "Fire is approaching rapidly. Evacuate NOW."),
                CommentTemplate(authorName: "Local Resident", content: "Leaving now. Where should we go?"),
                CommentTemplate(authorName: "Emergency Services", content: "Go to Central High School shelter. Buses available."),
                CommentTemplate(authorName: "Weather Alert", content: "Winds shifting. Fire moving faster than expected.")
            ]
        }
    }

    struct DailyPostTemplate {
        let authorName: String
        let authorAvatar: String
        let content: String
        let postType: CommunityPost.PostType
        let location: String
        let urgency: CommunityPost.UrgencyLevel
        let isVerified: Bool
    }

    struct CommentTemplate {
        let authorName: String
        let content: String
    }
}

struct StatChip: View {
    let icon: String
    let value: String
    let label: String

    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: icon)
                .font(.system(size: 12, weight: .medium))
                .foregroundColor(.appPrimary)

            Text(value)
                .font(.system(size: 14, weight: .bold, design: .rounded))
                .foregroundColor(.appTextPrimary)

            Text(label)
                .font(.system(size: 12, weight: .medium))
                .foregroundColor(.appTextSecondary)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 6)
        .background(Color.appCard.opacity(0.8))
        .cornerRadius(12)
    }
}

struct ModernFilterPill: View {
    let title: String
    let icon: String
    let isSelected: Bool
    let count: Int
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            HStack(spacing: 6) {
                Image(systemName: icon)
                    .font(.system(size: 12, weight: .medium))

                Text(title)
                    .font(.appSmall)
                    .fontWeight(.medium)

                if count > 0 {
                    Text("\(count)")
                        .font(.system(size: 10, weight: .bold, design: .rounded))
                        .padding(.horizontal, 6)
                        .padding(.vertical, 2)
                        .background(isSelected ? Color.white.opacity(0.3) : Color.appPrimary.opacity(0.3))
                        .cornerRadius(8)
                }
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 8)
            .background(isSelected ? Color.appPrimary : Color.appCard)
            .foregroundColor(isSelected ? .white : .appTextPrimary)
            .cornerRadius(16)
            .shadow(color: isSelected ? Color.appPrimary.opacity(0.3) : Color.clear, radius: 4, x: 0, y: 2)
        }
    }
}

struct ThreadCard: View {
    let post: CommunityPost
    let onAction: (PostAction) -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {

            HStack(spacing: 12) {

                ZStack {
                    Circle()
                        .fill(Color.appGradientPrimary)
                        .frame(width: 40, height: 40)

                    Image(systemName: post.authorAvatar)
                        .font(.system(size: 16, weight: .medium))
                        .foregroundColor(.white)
                }

                VStack(alignment: .leading, spacing: 2) {
                    HStack(spacing: 6) {
                        Text(post.authorName)
                            .font(.appSubheadline)
                            .fontWeight(.semibold)
                            .foregroundColor(.appTextPrimary)

                        if post.isVerified {
                            Image(systemName: "checkmark.seal.fill")
                                .font(.system(size: 12))
                                .foregroundColor(.appInfo)
                        }

                        Circle()
                            .fill(urgencyColor)
                            .frame(width: 6, height: 6)
                    }

                    HStack(spacing: 8) {
                        Text(timeAgoString(from: post.timestamp))
                            .font(.appSmall)
                            .foregroundColor(.appTextTertiary)

                        if let location = post.location {
                            HStack(spacing: 2) {
                                Image(systemName: "location.fill")
                                    .font(.system(size: 8))
                                Text(location)
                                    .font(.appSmall)
                            }
                            .foregroundColor(.appTextTertiary)
                        }
                    }
                }

                Spacer()

                PostTypeBadge(postType: post.postType, urgency: post.urgency)
            }
            .padding(.horizontal, 16)
            .padding(.top, 16)

            Text(cleanedContent)
                .font(.appBody)
                .foregroundColor(.appTextPrimary)
                .lineLimit(nil)
                .padding(.horizontal, 16)
                .padding(.top, 12)

            if !post.comments.isEmpty {
                CommentsPreview(comments: Array(post.comments.prefix(2)), totalCount: post.comments.count)
                    .padding(.horizontal, 16)
                    .padding(.top, 12)
            }

            HStack(spacing: 24) {

                Button(action: {
                    withAnimation(.appSpring) {
                        onAction(.like)
                    }
                }) {
                    HStack(spacing: 6) {
                        Image(systemName: post.isLikedByUser ? "heart.fill" : "heart")
                            .font(.system(size: 16, weight: .medium))
                            .foregroundColor(post.isLikedByUser ? .appError : .appTextSecondary)
                            .scaleEffect(post.isLikedByUser ? 1.1 : 1.0)

                        if post.likes > 0 {
                            Text("\(post.likes)")
                                .font(.appSmall)
                                .fontWeight(.medium)
                                .foregroundColor(post.isLikedByUser ? .appError : .appTextSecondary)
                        }
                    }
                }

                Button(action: { onAction(.comment) }) {
                    HStack(spacing: 6) {
                        Image(systemName: "bubble.left")
                            .font(.system(size: 16, weight: .medium))
                            .foregroundColor(.appTextSecondary)

                        if post.comments.count > 0 {
                            Text("\(post.comments.count)")
                                .font(.appSmall)
                                .fontWeight(.medium)
                                .foregroundColor(.appTextSecondary)
                        }
                    }
                }

                Button(action: { onAction(.share) }) {
                    Image(systemName: "square.and.arrow.up")
                        .font(.system(size: 16, weight: .medium))
                        .foregroundColor(.appTextSecondary)
                }

                Spacer()

                if post.isMyPost {
                    Button(action: { onAction(.delete) }) {
                        Image(systemName: "trash")
                            .font(.system(size: 14, weight: .medium))
                            .foregroundColor(.appError)
                    }
                }
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
        }
        .appCardStyle()
        .padding(.horizontal, 4)
    }

    private var urgencyColor: Color {
        switch post.urgency {
        case .low: return .appSuccess
        case .medium: return .appWarning
        case .high: return .appError
        case .critical: return .appError
        }
    }

    private var cleanedContent: String {

        return post.content
            .replacingOccurrences(of: "🚨 URGENT:", with: "")
            .replacingOccurrences(of: "🚨 MANDATORY EVACUATION:", with: "EVACUATION:")
            .replacingOccurrences(of: "🏠 SHELTER UPDATE:", with: "")
            .replacingOccurrences(of: "💧 Offering", with: "Offering")
            .replacingOccurrences(of: "🔥 FIRE UPDATE:", with: "")
            .replacingOccurrences(of: "🌤️ WEATHER UPDATE:", with: "")
            .replacingOccurrences(of: "💊 FREE MEDICATIONS:", with: "Free medications:")
            .replacingOccurrences(of: "🍎 FREE FOOD DISTRIBUTION:", with: "Free food:")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func timeAgoString(from date: Date) -> String {
        let interval = Date().timeIntervalSince(date)
        if interval < 3600 {
            let minutes = max(1, Int(interval / 60))
            return "\(minutes)m"
        } else if interval < 86400 {
            let hours = Int(interval / 3600)
            return "\(hours)h"
        } else {
            let days = Int(interval / 86400)
            return "\(days)d"
        }
    }
}

struct PostTypeBadge: View {
    let postType: CommunityPost.PostType
    let urgency: CommunityPost.UrgencyLevel

    var body: some View {
        HStack(spacing: 4) {
            Image(systemName: postType.icon)
                .font(.system(size: 10, weight: .medium))

            Text(shortTitle)
                .font(.system(size: 10, weight: .medium))
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 4)
        .background(backgroundColor)
        .foregroundColor(.white)
        .cornerRadius(8)
    }

    private var shortTitle: String {
        switch postType {
        case .help: return "Help"
        case .offer: return "Offer"
        case .info: return "Info"
        case .evacuation: return "Evac"
        case .shelter: return "Shelter"
        case .resources: return "Resources"
        }
    }

    private var backgroundColor: Color {
        switch urgency {
        case .low: return .appSuccess
        case .medium: return .appWarning
        case .high: return .appError
        case .critical: return .appError
        }
    }
}

struct CommentsPreview: View {
    let comments: [Comment]
    let totalCount: Int

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(comments) { comment in
                HStack(alignment: .top, spacing: 8) {
                    Circle()
                        .fill(Color.appTextTertiary.opacity(0.6))
                        .frame(width: 20, height: 20)
                        .overlay(
                            Text(String(comment.authorName.prefix(1)))
                                .font(.system(size: 10, weight: .medium))
                                .foregroundColor(.white)
                        )

                    VStack(alignment: .leading, spacing: 2) {
                        Text(comment.authorName)
                            .font(.appSmall)
                            .fontWeight(.medium)
                            .foregroundColor(.appTextSecondary)

                        Text(cleanedCommentContent(comment.content))
                            .font(.appSmall)
                            .foregroundColor(.appTextPrimary)
                            .lineLimit(2)
                    }

                    Spacer()
                }
            }

            if totalCount > 2 {
                Button("View all \(totalCount) replies") {

                }
                .font(.appSmall)
                .foregroundColor(.appPrimary)
            }
        }
        .padding(.vertical, 8)
        .padding(.horizontal, 12)
        .background(Color.appSurface.opacity(0.5))
        .cornerRadius(12)
    }

    private func cleanedCommentContent(_ content: String) -> String {
        return content
            .replacingOccurrences(of: "Thank you so much! This is a lifesaver.", with: "Thanks! This helps a lot.")
            .replacingOccurrences(of: "I can help distribute. Be there in 15 min.", with: "Can help distribute, be there soon")
            .replacingOccurrences(of: "We're in the area. Call 911 if immediate assistance needed.", with: "We're nearby. Call 911 if urgent.")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }
}

struct NewPostSheet: View {
    @Binding var content: String
    @Binding var postType: CommunityPost.PostType
    @Binding var urgency: CommunityPost.UrgencyLevel
    let onPost: () -> Void
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ZStack {
                Color.appGradientBackground.ignoresSafeArea()

                ScrollView {
                    VStack(spacing: 24) {

                        VStack(alignment: .leading, spacing: 12) {
                            Text("What's happening?")
                                .font(.appHeadline)
                                .foregroundColor(.appTextPrimary)

                            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 12) {
                                ForEach(CommunityPost.PostType.allCases, id: \.self) { type in
                                    Button(action: {
                                        withAnimation(.appEaseOut) {
                                            postType = type
                                        }
                                    }) {
                                        HStack(spacing: 8) {
                                            Image(systemName: type.icon)
                                                .font(.system(size: 14, weight: .medium))
                                                .foregroundColor(postType == type ? .white : .appTextSecondary)

                                            Text(type.rawValue.components(separatedBy: " ").first ?? type.rawValue)
                                                .font(.appSmall)
                                                .fontWeight(.medium)
                                                .foregroundColor(postType == type ? .white : .appTextPrimary)
                                        }
                                        .frame(maxWidth: .infinity)
                                        .padding(.vertical, 12)
                                        .background(postType == type ? Color.appPrimary : Color.appCard)
                                        .cornerRadius(12)
                                        .shadow(color: postType == type ? Color.appPrimary.opacity(0.3) : Color.clear, radius: 4, x: 0, y: 2)
                                    }
                                }
                            }
                        }

                        VStack(alignment: .leading, spacing: 12) {
                            Text("Priority Level")
                                .font(.appSubheadline)
                                .foregroundColor(.appTextPrimary)

                            HStack(spacing: 8) {
                                ForEach(CommunityPost.UrgencyLevel.allCases, id: \.self) { level in
                                    Button(action: {
                                        withAnimation(.appEaseOut) {
                                            urgency = level
                                        }
                                    }) {
                                        Text(level.rawValue)
                                            .font(.appSmall)
                                            .fontWeight(.medium)
                                            .padding(.vertical, 8)
                                            .padding(.horizontal, 12)
                                            .background(urgency == level ? urgencyColor(level) : Color.appCard)
                                            .foregroundColor(urgency == level ? .white : .appTextPrimary)
                                            .cornerRadius(16)
                                    }
                                }
                            }
                        }

                        VStack(alignment: .leading, spacing: 12) {
                            Text("Your Message")
                                .font(.appSubheadline)
                                .foregroundColor(.appTextPrimary)

                            ZStack(alignment: .topLeading) {
                                RoundedRectangle(cornerRadius: 16)
                                    .fill(Color.appCard)
                                    .frame(minHeight: 120)

                                if content.isEmpty {
                                    Text("Share what's happening in your area...")
                                        .font(.appBody)
                                        .foregroundColor(.appTextTertiary)
                                        .padding(.top, 16)
                                        .padding(.leading, 16)
                                }

                                TextEditor(text: $content)
                                    .padding(16)
                                    .background(Color.clear)
                                    .foregroundColor(.appTextPrimary)
                                    .font(.appBody)
                                    .accentColor(.appPrimary)
                                    .scrollContentBackground(.hidden)
                            }
                        }

                        Spacer(minLength: 100)
                    }
                    .padding(20)
                }
            }
            .navigationTitle("New Post")
            .navigationBarTitleDisplayMode(.inline)
            .toolbarBackground(Color.appSurface, for: .navigationBar)
            .toolbarBackground(.visible, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Cancel") {
                        dismiss()
                    }
                    .foregroundColor(.appTextSecondary)
                }

                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Post") {
                        onPost()
                    }
                    .font(.appSubheadline)
                    .fontWeight(.semibold)
                    .foregroundColor(.appPrimary)
                    .disabled(content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                    .opacity(content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? 0.5 : 1.0)
                }
            }
        }
    }

    private func urgencyColor(_ level: CommunityPost.UrgencyLevel) -> Color {
        switch level {
        case .low: return .appSuccess
        case .medium: return .appWarning
        case .high: return .appError
        case .critical: return .appError
        }
    }
}

struct CommentsView: View {
    let post: CommunityPost
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ZStack {
                Color.appGradientBackground.ignoresSafeArea()

                ScrollView {
                    VStack(spacing: 16) {

                        ThreadCard(post: post) { _ in }

                        ForEach(post.comments) { comment in
                            CommentRow(comment: comment)
                        }
                    }
                    .padding(16)
                }
            }
            .navigationTitle("Comments")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .foregroundColor(.orange)
                }
            }
        }
    }
}

struct CommentRow: View {
    let comment: Comment
    let onDelete: (() -> Void)?
    @State private var isLiked = false
    @State private var likeCount: Int

    init(comment: Comment, onDelete: (() -> Void)? = nil) {
        self.comment = comment
        self.onDelete = onDelete
        self._likeCount = State(initialValue: comment.likes)
    }

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: "person.circle.fill")
                .font(.title3)
                .foregroundColor(.appTextSecondary)

            VStack(alignment: .leading, spacing: 4) {
                HStack {
                    Text(comment.authorName)
                        .font(.appSubheadline)
                        .fontWeight(.medium)
                        .foregroundColor(.appTextPrimary)

                    Spacer()

                    Text(timeAgoString(from: comment.timestamp))
                        .font(.appSmall)
                        .foregroundColor(.appTextTertiary)
                }

                Text(comment.content)
                    .font(.appBody)
                    .foregroundColor(.appTextPrimary)

                HStack {
                    Button(action: {
                        isLiked.toggle()
                        if isLiked {
                            likeCount += 1
                        } else {
                            likeCount -= 1
                        }
                    }) {
                        Image(systemName: isLiked ? "heart.fill" : "heart")
                            .font(.appSmall)
                            .foregroundColor(isLiked ? .appError : .appTextSecondary)
                    }

                    Text("\(likeCount)")
                        .font(.appSmall)
                        .foregroundColor(isLiked ? .appError : .appTextSecondary)

                    Button(action: {
                        shareComment(comment)
                    }) {
                        Image(systemName: "square.and.arrow.up")
                            .font(.appSmall)
                            .foregroundColor(.appInfo)
                    }

                    Spacer()

                    if comment.authorName == "You" {
                        Button(action: {
                            onDelete?()
                        }) {
                            Image(systemName: "trash")
                                .font(.appSmall)
                                .foregroundColor(.appError)
                        }
                    }
                }
            }
        }
        .padding(12)
        .background(Color.appCard)
        .cornerRadius(8)
    }

    private func timeAgoString(from date: Date) -> String {
        let interval = Date().timeIntervalSince(date)
        if interval < 3600 {
            let minutes = Int(interval / 60)
            return "\(minutes)m ago"
        } else if interval < 86400 {
            let hours = Int(interval / 3600)
            return "\(hours)h ago"
        } else {
            let days = Int(interval / 86400)
            return "\(days)d ago"
        }
    }

    private func shareComment(_ comment: Comment) {
        let shareText = "💬 \(comment.authorName): \(comment.content)\n\n📱 Shared from Ignis - Wildfire Community App"

        let activityVC = UIActivityViewController(
            activityItems: [shareText],
            applicationActivities: nil
        )

        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = windowScene.windows.first {
            window.rootViewController?.present(activityVC, animated: true)
        }
    }
}

struct PostDetailView: View {
    let post: CommunityPost
    let onAction: (PostAction) -> Void
    let onCommentsUpdate: ([Comment]) -> Void
    @Environment(\.dismiss) private var dismiss
    @State private var newComment = ""
    @State private var comments: [Comment]

    init(post: CommunityPost, onAction: @escaping (PostAction) -> Void, onCommentsUpdate: @escaping ([Comment]) -> Void) {
        self.post = post
        self.onAction = onAction
        self.onCommentsUpdate = onCommentsUpdate
        self._comments = State(initialValue: post.comments)
        self._newComment = State(initialValue: "")
    }

    var body: some View {
        NavigationStack {
            ZStack {
                Color.appGradientBackground.ignoresSafeArea(.all, edges: .all)

                ScrollView {
                    VStack(spacing: 20) {

                        VStack(alignment: .leading, spacing: 16) {

                            HStack {
                                Image(systemName: post.authorAvatar)
                                    .font(.title2)
                                    .foregroundColor(post.postType.color)

                                VStack(alignment: .leading, spacing: 2) {
                                    HStack {
                                        Text(post.authorName)
                                            .font(.appHeadline)
                                            .foregroundColor(.appTextPrimary)

                                        if post.isVerified {
                                            Image(systemName: "checkmark.seal.fill")
                                                .foregroundColor(.blue)
                                                .font(.caption)
                                        }
                                    }

                                    Text(timeAgoString(from: post.timestamp))
                                        .font(.appSmall)
                                        .foregroundColor(.appTextTertiary)
                                }

                                Spacer()

                                VStack(alignment: .trailing, spacing: 4) {
                                    HStack {
                                        Image(systemName: post.postType.icon)
                                            .foregroundColor(post.postType.color)
                                            .font(.caption)
                                        Text(post.postType.rawValue)
                                            .font(.caption)
                                            .foregroundColor(post.postType.color)
                                    }

                                    HStack {
                                        Circle()
                                            .fill(post.urgency.color)
                                            .frame(width: 8, height: 8)
                                        Text(post.urgency.rawValue)
                                            .font(.caption2)
                                            .foregroundColor(post.urgency.color)
                                    }
                                }
                            }

                            Text(post.content)
                                .font(.appBody)
                                .foregroundColor(.appTextPrimary)
                                .multilineTextAlignment(.leading)

                            if let location = post.location {
                                HStack {
                                    Image(systemName: "location.fill")
                                        .foregroundColor(.orange)
                                        .font(.caption)
                                    Text(location)
                                        .font(.caption)
                                        .foregroundColor(.gray)
                                }
                            }

                            HStack(spacing: 20) {
                                Button(action: {
                                    onAction(.like)
                                }) {
                                    HStack(spacing: 4) {
                                        Image(systemName: post.isLikedByUser ? "heart.fill" : "heart")
                                            .foregroundColor(post.isLikedByUser ? .red : .gray)
                                        Text("\(post.likes)")
                                            .font(.caption)
                                            .foregroundColor(post.isLikedByUser ? .red : .gray)
                                    }
                                }

                                Button(action: {

                                }) {
                                    HStack(spacing: 4) {
                                        Image(systemName: "message.fill")
                                            .foregroundColor(.blue)
                                        Text("\(post.comments.count)")
                                            .font(.caption)
                                            .foregroundColor(.blue)
                                    }
                                }

                                Button(action: {
                                    sharePostFromDetail(post)
                                }) {
                                    HStack(spacing: 4) {
                                        Image(systemName: "square.and.arrow.up")
                                            .foregroundColor(.green)
                                        Text("Share")
                                            .font(.caption)
                                            .foregroundColor(.green)
                                    }
                                }

                                if post.isMyPost {
                                    Button(action: { onAction(.delete) }) {
                                        HStack(spacing: 4) {
                                            Image(systemName: "trash")
                                                .foregroundColor(.red)
                                            Text("Delete")
                                                .font(.caption)
                                                .foregroundColor(.red)
                                        }
                                    }
                                }

                                Spacer()
                            }
                        }
                        .padding(20)
                        .appCardStyle()
                        .overlay(
                            RoundedRectangle(cornerRadius: 12)
                                .stroke(post.postType.color.opacity(0.3), lineWidth: 1)
                        )

                        VStack(alignment: .leading, spacing: 16) {
                            HStack {
                                Text("Comments (\(comments.count))")
                                    .font(.appHeadline)
                                    .foregroundColor(.appTextPrimary)
                                Spacer()
                            }

                            if comments.isEmpty {
                                Text("No comments yet. Be the first to comment!")
                                    .font(.appBody)
                                    .foregroundColor(.appTextSecondary)
                                    .padding()
                                    .frame(maxWidth: .infinity)
                                    .background(Color.appCard)
                                    .cornerRadius(8)
                            } else {
                                LazyVStack(spacing: 12) {
                                    ForEach(comments) { comment in
                                        CommentRow(comment: comment) {

                                            if let index = comments.firstIndex(where: { $0.id == comment.id }) {
                                                comments.remove(at: index)
                                                updatePostComments()
                                            }
                                        }
                                    }
                                }
                            }

                            VStack(spacing: 12) {
                                HStack {
                                    Text("Add a comment")
                                        .font(.appSubheadline)
                                        .foregroundColor(.appTextPrimary)
                                    Spacer()
                                }

                                HStack {
                                    TextField("Write a comment...", text: $newComment)
                                        .padding(.horizontal, 16)
                                        .padding(.vertical, 12)
                                        .background(Color.appCard)
                                        .foregroundColor(.appTextPrimary)
                                        .cornerRadius(8)
                                        .overlay(
                                            RoundedRectangle(cornerRadius: 8)
                                                .stroke(Color.appBorder, lineWidth: 1)
                                        )

                                    Button(action: {
                                        addComment()
                                    }) {
                                        Text("Post")
                                            .font(.appSubheadline)
                                            .fontWeight(.medium)
                                            .foregroundColor(.white)
                                            .padding(.horizontal, 16)
                                            .padding(.vertical, 12)
                                            .background(Color.appPrimary)
                                            .cornerRadius(8)
                                    }
                                    .disabled(newComment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                                }
                            }
                            .padding(.top, 8)
                        }
                    }
                    .padding(16)
                }
            }
            .navigationTitle("Post Details")
            .navigationBarTitleDisplayMode(.inline)
            .toolbarBackground(Color.appBackground, for: .navigationBar)
            .toolbarBackground(.visible, for: .navigationBar)
            .toolbarColorScheme(.dark, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .foregroundColor(.appPrimary)
                }
            }
            .onAppear {

                print("PostDetailView appeared for post: \(post.authorName)")
            }
            .background(Color.appBackground)
        }
    }

    private func addComment() {
        let comment = Comment(
            authorName: "You",
            content: newComment.trimmingCharacters(in: .whitespacesAndNewlines),
            timestamp: Date(),
            likes: 0
        )

        comments.append(comment)
        newComment = ""
        updatePostComments()
    }

    private func updatePostComments() {

        onCommentsUpdate(comments)
    }

    private func sharePostFromDetail(_ post: CommunityPost) {

        let shareText = createDetailedShareText(for: post)

        let activityVC = UIActivityViewController(
            activityItems: [shareText],
            applicationActivities: nil
        )

        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = windowScene.windows.first {
            window.rootViewController?.present(activityVC, animated: true)
        }
    }

    private func createDetailedShareText(for post: CommunityPost) -> String {
        var shareText = "🔥 Wildfire Community Update\n\n"
        shareText += "📝 \(post.postType.rawValue)\n"
        shareText += "👤 \(post.authorName)\n"
        shareText += "🚨 Urgency: \(post.urgency.rawValue)\n"

        if let location = post.location {
            shareText += "📍 Location: \(location)\n"
        }

        shareText += "\n💬 \(post.content)\n"
        shareText += "\n💬 Comments (\(comments.count)):\n"

        for (index, comment) in comments.prefix(3).enumerated() {
            shareText += "  \(index + 1). \(comment.authorName): \(comment.content)\n"
        }

        if comments.count > 3 {
            shareText += "  ... and \(comments.count - 3) more comments\n"
        }

        shareText += "\n❤️ Likes: \(post.likes)\n"
        shareText += "\n📱 Shared from Ignis - Wildfire Community App"

        return shareText
    }

    private func timeAgoString(from date: Date) -> String {
        let interval = Date().timeIntervalSince(date)
        if interval < 3600 {
            let minutes = Int(interval / 60)
            return "\(minutes)m ago"
        } else if interval < 86400 {
            let hours = Int(interval / 3600)
            return "\(hours)h ago"
        } else {
            let days = Int(interval / 86400)
            return "\(days)d ago"
        }
    }
}

enum PostAction {
    case like
    case comment
    case share
    case delete
}

#Preview {
    CommunityThreadsView()
}
